Repository BkrTech101-InnovaMind/tadllal-app, pull requests merged in 2023-08, with the labels that each got.

#9 feat(User and Admin controller):Setting up Admin and User Authenticat…
  API/README.md
  API/app/Http/Controllers/Admin/AuthController.php
  API/app/Http/Controllers/AuthController.php
  API/app/Http/Kernel.php
  API/app/Http/Middleware/AdminMiddleware.php
  API/app/Http/Requests/LoginUserRequest.php
  API/app/Http/Requests/StoreUserRequest.php
  API/app/Http/Requests/UpdateUserRequest.php
  API/app/Models/User.php
  API/app/Traits/HttpResponses.php
  API/database/factories/UserFactory.php
  API/database/migrations/2014_10_12_000000_create_users_table.php
  API/database/seeders/DatabaseSeeder.php
  API/routes/api.php
  API/routes/web.php
Labels: API

#11 5 authentication page
  app/assets/icons/arrow_left.svg
  app/assets/images/login.png
  app/lib/main.dart
  app/lib/pages/auth_pages/auth_pages.dart
  app/lib/pages/auth_pages/code_auth_page/code_auth_page.dart
  app/lib/pages/auth_pages/sign_in_page/sign_in_page.dart
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/auth_pages/sign_up_page/sign_up_page.dart
  app/lib/pages/auth_pages/sign_up_page/widgets/sign_up_form.dart
  app/lib/pages/auth_pages/widgets/share_button.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement

#22 feat(TypesController): Implementing Real Estate Types API Functionalityt
  API/app/Http/Controllers/Admin/TypesController.php
  API/app/Http/Controllers/TypesController.php
  API/app/Http/Resources/TypesResource.php
  API/routes/api.php
Labels: API

#23 feat(LocationsController):Implementing Real Locations Functionality f…
  API/app/Http/Controllers/Admin/LocationsController.php
  API/app/Http/Controllers/LocationsController.php
  API/app/Http/Resources/LocatiosResource.php
  API/routes/api.php
Labels: API

#24 feat(Orders): Building API for Real Estate Orders and Admin Approval
  API/app/Http/Controllers/Admin/OrdersController.php
  API/app/Http/Controllers/OrdersController.php
  API/app/Http/Resources/OrdersResource.php
  API/app/Models/Orders.php
  API/database/migrations/2023_08_05_020553_create_orders_table.php
  API/routes/api.php
Labels: API

#25 feat(Real Estate filters):Implementing Filters API for Customized Rea…
  API/app/Http/Controllers/RealEstateController.php
  API/app/Models/RealEstate.php
  API/routes/api.php
Labels: API

#27 12 state management
  app/.gitignore
  app/android/app/build.gradle
  app/android/app/src/main/AndroidManifest.xml
  app/android/gradle/wrapper/gradle-wrapper.properties
  app/lib/main.dart
  app/lib/methods/auth_provider.dart
  app/lib/methods/note_for_futur.dart
  app/lib/pages/auth_pages/auth_pages.dart
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/auth_pages/sign_up_page/widgets/sign_up_form.dart
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/home_page/widgets/real_estates.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, state management

#31 28 sign in splash screen
  app/lib/pages/success_sign_in_splash_screen/success_sign_in_splash_screen.dart
  app/lib/pages/success_sign_in_splash_screen/widgets/chose_fav_page.dart
  app/lib/pages/success_sign_in_splash_screen/widgets/complete_profile_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, UI

#34 3 button navigation bar
  app/assets/icons/favorites-icon.svg
  app/assets/icons/home-icon.svg
  app/assets/icons/search-icon.svg
  app/assets/icons/user-icon.svg
  app/lib/main.dart
  app/lib/pages/navigation_page/navigation_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, UI

#36 35 user page
  app/lib/pages/navigation_page/navigation_page.dart
  app/lib/pages/user_page/profile_page.dart
Labels: enhancement, UI

#38 37 user profile editor
  app/lib/pages/profile_editor_page/profile_editor_page.dart
  app/lib/pages/success_sign_in_splash_screen/success_sign_in_splash_screen.dart
  app/lib/pages/success_sign_in_splash_screen/widgets/chose_fav_page.dart
  app/lib/pages/success_sign_in_splash_screen/widgets/complete_profile_page.dart
  app/lib/pages/user_page/profile_page.dart
Labels: enhancement, UI

#44 contact_pop_up
  app/lib/components/contact_us_pop_up.dart
Labels: enhancement, UI

#46 45 add user page
  app/lib/pages/add_user_page/add_user_page.dart
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/user_page/profile_page.dart
Labels: enhancement, UI

#47 40 change password pop up
  app/lib/components/change_password_pop_up.dart
  app/lib/pages/user_page/profile_page.dart
Labels: enhancement, UI

#53 41 forget password page
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/forget_password_page/forget_password_page.dart
Labels: enhancement, UI

#54 49 single real estate page
  app/lib/components/order_pop_up.dart
  app/lib/pages/home_page/widgets/real_estates.dart
  app/lib/pages/real_estate_details_page/real_estate_details_page.dart
Labels: enhancement, UI

#55 42 search page
  app/lib/pages/navigation_page/navigation_page.dart
  app/lib/pages/search_page/search_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, UI

#56 43 favorites page
  app/lib/main.dart
  app/lib/methods/in_intro_tour_preferences.dart
  app/lib/pages/favorites_page/favorites_page.dart
  app/lib/pages/navigation_page/navigation_page.dart
  app/lib/pages/search_page/search_page.dart
  app/lib/utils/in_intro_tour.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, UI

#57 48 change user preferences
  app/lib/pages/change_user_preferences_page/change_user_preferences_page.dart
  app/lib/pages/user_page/profile_page.dart
Labels: enhancement, UI

#59 50 most requisted services page
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/most_requested_services_page/most_requested_services_page.dart
Labels: enhancement, UI

#60 58 single service page
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/most_requested_services_page/most_requested_services_page.dart
  app/lib/pages/single_service_page/single_service_page.dart
Labels: enhancement, UI

#63 51 general services page
  app/lib/pages/general_services_page/general_services_page.dart
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/most_requested_services_page/most_requested_services_page.dart
  app/lib/pages/single_sub_service_page/single_sub_service_page.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: enhancement, UI

#66 62 single general services page
  app/lib/pages/general_services_page/general_services_page.dart
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/single_general_services_page/single_general_services_page.dart
Labels: enhancement, UI

#67 52 notification page
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/notification_page/notification_page.dart
Labels: enhancement, UI

#69 feat(admin v0)
  API/.env.example
  API/app/Http/Controllers/Admin/ConstructionServiceController.php
  API/app/Http/Controllers/Admin/LocationsController.php
  API/app/Http/Controllers/Admin/RealEstateController.php
  API/app/Http/Controllers/Admin/SubConstructionServiceController.php
  API/app/Http/Controllers/Admin/TypesController.php
  API/app/Http/Controllers/Admin/UsersController.php
  API/app/Http/Controllers/AuthController.php
  API/app/Http/Kernel.php
  API/app/Http/Middleware/VerifyCsrfToken.php
  API/app/Http/Requests/UpdateRealEstateRequest.php
  API/app/Http/Resources/UserResource.php
  API/config/cors.php
  API/public/.htaccess
  API/routes/api.php
Labels: API

#73 68 app starter intro screen
  app/assets/images/logo.png
  app/assets/images/no-text-logo.png
  app/lib/pages/app_starter_intro_screen/app_starter_intro_screen.dart
  app/lib/pages/app_starter_intro_screen/widgets/on_boarding_screen.dart
  app/lib/pages/app_starter_intro_screen/widgets/on_boarding_splash.dart
Labels: enhancement, UI

#82 75-app-merging-level
  API/database/migrations/2023_08_12_020739_create_services_orders_table.php
  API/database/seeders/DatabaseSeeder.php
  app/lib/components/change_password_pop_up.dart
  app/lib/components/order_pop_up.dart
  app/lib/config/global.dart
  app/lib/main.dart
  app/lib/model/api_molels/data.dart
  app/lib/model/api_molels/error_response.dart
  app/lib/model/api_molels/user.dart
  app/lib/pages/auth_pages/code_auth_page/code_auth_page.dart
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/auth_pages/sign_up_page/sign_up_page.dart
  app/lib/pages/auth_pages/sign_up_page/widgets/sign_up_form.dart
  app/lib/pages/change_user_preferences_page/change_user_preferences_page.dart
  app/lib/pages/favorites_page/favorites_page.dart
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/real_estate_details_page/real_estate_details_page.dart
  app/lib/pages/single_sub_service_page/single_sub_service_page.dart
  app/lib/pages/splash/splash_screen.dart
  app/lib/pages/splash/success_sign_in_splash_screen/widgets/complete_profile_page.dart
  app/lib/services/api/dio_api.dart
  app/lib/services/dio_helper.dart
  app/lib/widgets/LodingUi/make_order_dialog.dart
  app/lib/widgets/error_dialog.dart
  app/lib/widgets/sinin_sinup_dialog.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: documentation, API, state management, UI

#84 83 add new featurs to admin dashboard
  API/app/Http/Controllers/Admin/LocationsController.php
  API/app/Http/Controllers/Admin/RealEstateController.php
  API/app/Http/Controllers/Admin/TypesController.php
  API/app/Http/Controllers/AuthController.php
  API/app/Http/Resources/ConstructionServiceResource.php
  API/app/Http/Resources/OrdersResource.php
  API/app/Http/Resources/RealEstateResource.php
  API/app/Http/Resources/RealEstateWithCommentsResource.php
  API/app/Http/Resources/ServicesOrdersResource.php
  API/app/Http/Resources/SubConstructionServiceResource.php
  API/app/Http/Resources/TypesResource.php
  API/app/Http/Resources/UserPerferenceResource.php
  API/app/Http/Resources/UserResource.php
  dashboard/src/Components/CustomTable.jsx
  dashboard/src/api/api.js
  dashboard/src/api/filtersData.js
  dashboard/src/api/tadllal-app.code-workspace
  dashboard/src/data/arrays.js
  dashboard/src/pages/Locations/index.jsx
  dashboard/src/pages/Orders/index.jsx
  dashboard/src/pages/RealEstate/index.jsx
  dashboard/src/pages/Services/index.jsx
  dashboard/src/pages/Types/index.jsx
  dashboard/src/pages/Users/index.jsx
  dashboard/src/styles/globals.css
Labels: API

#87 74-app-modifying-level
  app/android/app/src/debug/AndroidManifest.xml
  app/android/app/src/main/AndroidManifest.xml
  app/android/app/src/main/java/com/tadllal/tadllal/MainActivity.java
  app/ios/Runner/Info.plist
  app/lib/components/forget_password_status.dart
  app/lib/config/global.dart
  app/lib/main.dart
  app/lib/model/api_molels/sinin_sinup_request.dart
  app/lib/model/api_molels/user.dart
  app/lib/model/real_estate.dart
  app/lib/pages/add_user_page/add_user_page.dart
  app/lib/pages/auth_pages/sign_in_page/widgets/sign_in_form.dart
  app/lib/pages/auth_pages/sign_up_page/widgets/sign_up_form.dart
  app/lib/pages/favorites_page/favorites_page.dart
  app/lib/pages/forget_password_page/forget_password_page.dart
  app/lib/pages/home_page/home_page.dart
  app/lib/pages/notification_page/notification_page.dart
  app/lib/pages/real_estate_details_page/real_estate_details_page.dart
  app/lib/pages/single_sub_service_page/single_sub_service_page.dart
  app/lib/pages/splash/splash_screen.dart
  app/lib/pages/splash/success_sign_in_splash_screen/widgets/chose_fav_page.dart
  app/lib/pages/splash/success_sign_in_splash_screen/widgets/complete_profile_page.dart
  app/lib/pages/user_page/profile_page.dart
  app/lib/services/api/dio_api.dart
  app/lib/services/dio_helper.dart
  app/lib/services/helpers.dart
  app/lib/services/http.dart
  app/lib/widgets/forget_password_dialog.dart
  app/lib/widgets/make_order_dialog.dart
  app/lib/widgets/sinin_sinup_dialog.dart
  app/pubspec.lock
  app/pubspec.yaml
Labels: API, UI
